# Generated by Django 2.2.10 on 2020-02-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faktura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=100)),
                ('nazwa', models.CharField(max_length=100)),
                ('data_wystawienia', models.DateField()),
                ('kwota_netto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat', models.IntegerField()),
                ('miejsce', models.CharField(choices=[('Żagań', 'Żagań'), ('Krasiczyn', 'Krasiczyn')], max_length=30)),
                ('plik', models.ImageField(upload_to='')),
            ],
        ),
    ]
