# Generated by Django 2.2.10 on 2020-02-08 15:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Miejsce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejsce', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=100)),
                ('nazwa', models.CharField(max_length=100)),
                ('data_wystawienia', models.DateField()),
                ('kwota_netto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat', models.DecimalField(choices=[(Decimal('0.00'), '0'), (Decimal('0.08'), '8'), (Decimal('0.05'), '5'), (Decimal('0.23'), '23')], decimal_places=2, max_digits=10)),
                ('plik', models.FileField(upload_to='')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('miejsce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faktury.Miejsce')),
            ],
        ),
    ]
