# Generated by Django 2.2.10 on 2020-02-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0002_auto_20200205_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='vat',
            field=models.DecimalField(choices=[('23', '23'), ('8', '8'), ('0', '0'), ('5', '5')], decimal_places=2, max_digits=10),
        ),
    ]
