# Generated by Django 2.2.10 on 2020-02-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0003_auto_20200207_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='vat',
            field=models.IntegerField(),
        ),
    ]
