# Generated by Django 2.2.10 on 2020-02-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0005_auto_20200207_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='vat',
            field=models.DecimalField(choices=[(0.23, '23'), (0.08, '8'), (0.0, '0'), (0.05, '5')], decimal_places=2, max_digits=10),
        ),
    ]
