# Generated by Django 2.2.10 on 2020-02-07 19:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0006_auto_20200207_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='plik',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='vat',
            field=models.DecimalField(choices=[(Decimal('0.23'), '23')], decimal_places=2, max_digits=10),
        ),
    ]
